name: Self-test the HEAD

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  selftest_head:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: install
        run: sudo ln -sf "$PWD/pls/pls" /usr/local/bin/pls
      - name: selftest
        run: ./run_selftest.sh
